allowBuilds:
  esbuild: true
  msw: true
  sharp: true
  unrs-resolver: true

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - esbuild
  - msw

overrides:
  '@hono/node-server@<1.19.10': '>=1.19.10'
  '@hono/node-server@<1.19.13': '>=1.19.13'
  better-auth@<1.6.2: '>=1.6.2'
  brace-expansion@<1.1.13: '>=1.1.13'
  brace-expansion@>=4.0.0 <5.0.5: '>=5.0.5'
  brace-expansion@>=5.0.0 <5.0.6: '>=5.0.6'
  defu@<=6.1.4: '>=6.1.5'
  drizzle-orm@<0.45.2: '>=0.45.2'
  esbuild@<=0.24.2: '>=0.25.0'
  express-rate-limit@>=8.2.0 <8.2.2: '>=8.2.2'
  fast-uri@<=3.1.0: '>=3.1.1'
  fast-uri@<=3.1.1: '>=3.1.2'
  flatted@<3.4.0: '>=3.4.0'
  flatted@<=3.4.1: '>=3.4.2'
  hono@<4.12.12: '>=4.12.12'
  hono@<4.12.14: '>=4.12.14'
  hono@<4.12.16: '>=4.12.16'
  hono@<4.12.18: '>=4.12.18'
  hono@<4.12.4: '>=4.12.4'
  hono@<4.12.7: '>=4.12.7'
  hono@>=4.0.0 <=4.12.11: '>=4.12.12'
  ip-address@<=10.1.0: '>=10.1.1'
  kysely@<=0.28.13: '>=0.28.14'
  kysely@>=0.26.0 <0.28.17: '>=0.28.17'
  kysely@>=0.26.0 <=0.28.11: '>=0.28.12'
  lodash@<=4.17.23: '>=4.18.0'
  lodash@>=4.0.0 <=4.17.23: '>=4.18.0'
  next@>=16.0.0 <16.2.5: '>=16.2.5'
  next@>=16.0.0 <16.2.6: '>=16.2.6'
  next@>=16.0.0-beta.0 <16.1.7: '>=16.1.7'
  next@>=16.0.0-beta.0 <16.2.3: '>=16.2.3'
  next@>=16.0.1 <16.1.7: '>=16.1.7'
  path-to-regexp@>=8.0.0 <8.4.0: '>=8.4.0'
  picomatch@<2.3.2: '>=2.3.2'
  picomatch@>=4.0.0 <4.0.4: '>=4.0.4'
  postcss@<8.5.10: '>=8.5.10'
  qs@>=6.11.1 <=6.15.1: '>=6.15.2'
  undici@>=7.0.0 <7.24.0: '>=7.24.0'
  undici@>=7.17.0 <7.24.0: '>=7.24.0'
  vite@>=7.0.0 <=7.3.1: '>=7.3.2'
  vite@>=7.1.0 <=7.3.1: '>=7.3.2'
  ws@>=8.0.0 <8.20.1: '>=8.20.1'
