import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";
import { warpEmailSchema } from "./lib/schemas/common";

export const env = createEnv({
  server: {
    DATABASE_URL: z.url(),
    // B.C. See betterauth docs https://better-auth.com/docs/installation
    BETTER_AUTH_URL: z.url(),
    BETTER_AUTH_SECRET: z.string().min(1),
    // B.C. These are generated by creating an OAuth application on ms
    // I forget if it's entra or wherever the source is
    MICROSOFT_CLIENT_ID: z.string().min(1),
    MICROSOFT_CLIENT_SECRET: z.string().min(1),
    MICROSOFT_TENANT_ID: z.string().min(1),
    // B.C. These can be generated by creating an OAuth app on Atlassian
    ATLASSIAN_CLIENT_ID: z.string().min(1),
    ATLASSIAN_CLIENT_SECRET: z.string().min(1),
    ATLASSIAN_EMAIL_ADDRESS: z.email().optional(), // B.C. For local testing
    // B.C. I'm not a fan of the built in node_env for these things.
    APP_ENV: z.enum(["test", "development", "production"]),
    WARP_TEST_USERNAME: warpEmailSchema.optional(),
    WARP_TEST_PASSWORD: z.string().min(1).optional(),
  },
  client: {
    NEXT_PUBLIC_ENABLE_MSW_MOCK: z.coerce.boolean(),
  },
  runtimeEnv: {
    DATABASE_URL: process.env.DATABASE_URL,
    BETTER_AUTH_URL: process.env.BETTER_AUTH_URL,
    BETTER_AUTH_SECRET: process.env.BETTER_AUTH_SECRET,
    MICROSOFT_CLIENT_ID: process.env.MICROSOFT_CLIENT_ID,
    MICROSOFT_CLIENT_SECRET: process.env.MICROSOFT_CLIENT_SECRET,
    MICROSOFT_TENANT_ID: process.env.MICROSOFT_TENANT_ID,
    ATLASSIAN_CLIENT_ID: process.env.ATLASSIAN_CLIENT_ID,
    ATLASSIAN_CLIENT_SECRET: process.env.ATLASSIAN_CLIENT_SECRET,
    ATLASSIAN_EMAIL_ADDRESS: process.env.ATLASSIAN_EMAIL_ADDRESS,
    APP_ENV: process.env.APP_ENV,
    NEXT_PUBLIC_ENABLE_MSW_MOCK: process.env.NEXT_PUBLIC_ENABLE_MSW_MOCK,
    WARP_TEST_USERNAME: process.env.WARP_TEST_USERNAME,
    WARP_TEST_PASSWORD: process.env.WARP_TEST_PASSWORD,
  },
});
